# Copyright 2020-2024 The MathWorks, Inc.

name: Publish jupyter-matlab-proxy to PyPI
on:
  release:
    types: [created]

jobs:
  call-unit-tests:
    # Only run release jobs on tags which have `jupyter-matlab-proxy` in them
    if: ${{ contains(github.ref, 'jupyter-matlab-proxy') }}
    # Run unit tests
    uses: ./.github/workflows/run-unit-tests.yml
    secrets: inherit

  build_and_publish_pypi:
    needs: [call-unit-tests]
    if: success()
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    environment:
      name:  pypi
      url: https://pypi.org/project/jupyter-matlab-proxy

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Python build dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install wheel hatch

      - name: Build Source and Binary wheel distributions
        run: python3 -m hatch build -t wheel

      - name: Publish to PyPI.
        uses: pypa/gh-action-pypi-publish@release/v1